config/routes.rb
Rails.application.routes.draw do
  get 'doses/index'

  get 'doses/create'

  get 'doses/new'

  get 'doses/edit'

  get 'doses/show'

  get 'doses/update'

  get 'doses/destroy'

  root 'cocktails#index'
  resources :cocktails

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: :true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  validates :description, uniqueness: true, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true

  belongs_to :cocktail
  belongs_to :ingredient

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses

  validates :name, uniqueness: :true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail= Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

private

  def cocktail_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<h1>Cocktails#index</h1>
<p>Find me in app/views/cocktails/index.html.erb</p>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

app/views/cocktails/show.html.erb
<%= link_to("ajouter un cocktail ?", new_cocktail_path) %>

<h3>Liste des restos </h3>
<% @cocktails.each do |cocktail| %>
<ol>
  <%= link_to cocktail.name, cocktail_path(cocktail) %>
  <%= link_to("modify?", edit_cocktail_path(cocktail)) %>
  <%= link_to("lache ton comm", new_cocktail_review_path(cocktail)) %>

  <%= link_to "Delete", cocktail_path(cocktail),
  method: :delete,
  data: { confirm: "Are you sure?" } %>
</ol>
<% end %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mistercocktail</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>

<%= yield %>

</body>
</html>